<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>UniversalMobileDesktop.Receiver</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Protocol\Protocol.csproj" />
    <ProjectReference Include="..\Transport\Transport.csproj" />
    <ProjectReference Include="..\Video\Video.csproj" />
    <ProjectReference Include="..\Input\Input.csproj" />
    <ProjectReference Include="..\FileTransfer\FileTransfer.csproj" />
  </ItemGroup>
  <ItemGroup Condition="Exists('..\ffmpeg8\ffmpeg-8.1.2-full_build-shared\bin')">
    <Content Include="..\ffmpeg8\ffmpeg-8.1.2-full_build-shared\bin\*.dll">
      <Link>ffmpeg\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
